# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        name: build package for pamooba
        deployment: test
        script:
          - wget https://github.com/berkholz/Helperfunctions/releases/download/v0.1/Helperfunctions-0.1.jar
          - mvn install:install-file -Dfile=./Helperfunctions-0.1.jar -DgroupId=org.berkholz -DartifactId=Helperfunctions -Dversion=0.1 -Dpackaging=jar
          - wget https://github.com/berkholz/ConfigurationFrameWork/releases/download/v0.1/configurationframework-0.1-jar-with-dependencies.jar
          - mvn install:install-file -Dfile=configurationframework-0.1-jar-with-dependencies.jar -DgroupId=org.berkholz -DartifactId=configurationframework -Dversion=0.1 -Dpackaging=jar
          - mvn package  
          - mvn -B clean install
          - curl -i -X POST --user "${BITBUCKET_REPO_OWNER}:${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/" --form files=@"target/PaMooBa-0.1-jar-with-dependencies.jar" --verbose


