# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        name: install Helperfunctions 
        script:
          - wget https://github.com/berkholz/Helperfunctions/releases/download/v0.1/Helperfunctions-0.1.jar
          - pwd 
          - ls -la 
          - mvn install:install-file -Dfile=./Helperfunctions-0.1.jar -DgroupId=org.berkholz -DartifactId=Helperfunctions -Dversion=0.1 -Dpackaging=jar
    - step:
        name: install ConfigurationFrameWork JAR file
        script:
          - wget https://github.com/berkholz/ConfigurationFrameWork/releases/download/v0.1/configurationframework-0.1-jar-with-dependencies.jar
          - pwd
          - ls -la
          - mvn install:install-file -Dfile=configurationframework-0.1-jar-with-dependencies.jar -DgroupId=org.berkholz -DartifactId=configurationframework -Dversion=0.1 -Dpackaging=jar
    - step:
        name: verify
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B verify # -B batch mode makes Maven less verbose
    - step:
        name: build package
        deployment: test
        script:
          - mvn package

